# Generated by Django 5.1.6 on 2025-02-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='title',
            field=models.CharField(default='', max_length=150, unique=True),
        ),
    ]
